import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

driver = webdriver.Chrome()
driver.get("https://app.myday.biz/login")
driver.maximize_window()
driver.find_element(By.NAME, value="email").send_keys('mokaddis.borhan@cliqpack.com')
time.sleep(2)
driver.find_element(By.NAME,value="password").send_keys('12345678')
time.sleep(2)
driver.find_element(By.XPATH,value="//button[@type='submit']").click()
time.sleep(3)
driver.find_element(By.XPATH,value="//span[normalize-space()='Property']").click()
time.sleep(3)
driver.find_element(By.XPATH,value="//button[normalize-space()='Add property']").click()
time.sleep(5)
driver.find_element(By.XPATH,value="//input[@name='reference']").send_keys('samman zim')
time.sleep(2)
driver.find_element(By.XPATH,value="//input[@name='address']").send_keys('Dhaka')
time.sleep(3)
driver.find_element(By.XPATH,value="//button[normalize-space()='Details']").click()
time.sleep(3)
driver.find_element(By.XPATH,value="//input[@name='building']").send_keys('Vinanda house')
time.sleep(1)
driver.find_element(By.XPATH,value="//input[@name='subject']").send_keys("SQA")
driver.find_element(By.XPATH,value="//input[@name='unit']").send_keys('04')
time.sleep(1)
driver.find_element(By.XPATH,value="//input[@name='number']").send_keys('221B')
time.sleep(2)
driver.find_element(By.XPATH,value="//input[@name='street']").send_keys('221')
time.sleep(2)
driver.find_element(By.XPATH,value="//input[@name='suburb']").send_keys('Dhaka')
time.sleep(2)
driver.find_element(By.XPATH,value="//input[@name='state']").send_keys('Dhaka')
time.sleep(2)
driver.find_element(By.XPATH,value="//input[@name='postcode']").send_keys('Bangladesh')
driver.find_element(By.TAG_NAME,value="body").send_keys(Keys.PAGE_DOWN)
time.sleep(2)
driver.find_element(By.TAG_NAME,value="body").send_keys(Keys.PAGE_DOWN)
time.sleep(2)
driver.find_element(By.TAG_NAME,value="body").send_keys(Keys.PAGE_DOWN)
driver.find_element(By.XPATH,value="//i[@class='fas fa-file-alt me-1']").click()
time.sleep(5)